### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by BuzZoiDk24**
So, I added the German translation to the assistant.

I'm a noob when it comes to coding und installed something like 'npm' for the first time. So I'm not sure if I edited the layout.tsx entirely correct.

I'm sure there are some typos but as a first version it hopefully works. Some texts got quite long compared to English and I'm not sure if there will be visual issues.

I didn't test it locally.

### CODE REVIEW

**Comment by SephHawkins** [comment]
This is amazing! Thank you very much for adding this in - I'll take a look at it this evening and get back to you.

**Comment by SephHawkins** [comment]
I added in the german flag (and made some minor changes to get certain keywords to show up correctly).

Overall, it looks good - there's definitely some places where the length causes some overflow, but I can work on fixing those over time.

I've pushed up the changes to the dev site if you want to take a look (https://dev-dot-twilight-imperium-360307.wm.r.appspot.com/). Regardless, I've approved the changes - feel free to squash and merge whenever and I'll push the changes to the main site once you do.

**Review by SephHawkins — APPROVED** [review]

**Comment by BuzZoiDk24** [comment]
Thank you for reviewing and putting it on the dev site. This helps a lot for testing purposes. I've seen already few typos and things I'd like to change. Will do so over the next few days.

I noticed that quite a few things are still in English, see screenshots attached (during status and agenda phase).

One general question I have is about the difference between "After an Angenda is Revealed" and "When an Agenda is Revealed". I'm not a native English speaker so I'm not certain if there is a big difference. For me it has the same meaning and it makes it in German even more confusing. 
That being said, it's written like that on the respective cards and I think I know what is meant. The first resolves the actions that might change the agenda and the second resolves when actions change the voting order or eliminate a player out of the voting (exhausting their planet cards). Still, it is a little confusing - in German at least. I'll probably change "When an agenda is revealed" to "Before the voting begins" or something similar in German.

Screenshot 2024-04-19 072419
Screenshot 2024-04-19 072953

**Comment by SephHawkins** [comment]
Yep, there's definitely a bunch of strings that I missed when I was doing the translation setup. I'll try to get those added in the next few days so that they can be translated.

In regards to "When an agenda..." vs. "After an agenda...", they refer to 2 distinct timing steps. "When" is something that occurs "at the same time" as the agenda being revealed and usually modifies the agenda in some way, and "After" is something that occurs after the agenda being revealed is done, and is some separate effect (a Rider or altering the voting).

As an example (from the [German TI wiki](https://twilight-imperium.fandom.com/de/wiki/Aktionskarten)), the Veto action card reads "Sobald eine Agenda aufgedeckt wird" and in English "When an agenda is revealed", and the Assassinate Representative action card reads "Nachdem eine Agenda aufgedeckt worden ist" and in English "After an agenda is revealed".

**Comment by BuzZoiDk24** [comment]
Ah, I see the error now. In my translation I accidentally used for both phrases "worden ist" which makes it basically identical from a timing perspective. "Wird" and "worden ist" makes the difference. Woops :)

Thanks for pointing it out.

**Comment by SephHawkins** [comment]
Added in a bunch of the missing strings and pushed up to the dev site. Looking at the file diff for [en.json](https://github.com/ti-assistant/ti-assistant/pull/30/files#diff-87da8e320fb9a0701787ab8b1654186be2a8986e32a1972b65a986144c3ed3c9) is probably going to be the easiest way to find all the added things.

Let me know if you have any questions or spot anything else I missed.

**Comment by BuzZoiDk24** [comment]
I updated the translation files, getting more and more used to the usage of git bash, so now it's only one commit and not several for each file change. ;) 

It should be ready for merging. But I don't see an option here. Instead it says "Only those with write access to this repository can merge pull requests." Do I need to do it in another way?

**Comment by SephHawkins** [comment]
Looks like there's some extra permissions rules for "organizations", which is what this is set up as. I sent you an invite - once you accept that I may need to grant you permission on the repository. Once that's done you should be able to merge it in.

**Comment by SephHawkins** [comment]
Ok - updated the permissions. You should be good to merge it in.

**Comment by BuzZoiDk24** [comment]
Done :)

**Comment by SephHawkins** [comment]
Awesome! Btw, what name would you like added to the Supporters page? Happy to add your GitHub username or whatever other name you'd like.

**Comment by BuzZoiDk24** [comment]
My GitHub username is fine. Thanks!

**Comment by BuzZoiDk24** [comment]
Thanks for putting it online 👍 

Of course, there are still some open topics like overflowing texts, some texts still in English etc. What would be best practice to keep track of these and any other additional feedback, maybe also from other users? I thought of opening a general German-translation ticket in the Issues repository

**Pull request merged**
